### ISSUE TITLE
TwitchIrcClient not included in NuGet package

### ISSUE THREAD

**Issue by notepid** [IrcDotNet/IrcDotNet#11]
Seems like the TwitchIrcClient is not included in the 0.5.0 NuGet package.

**Comment by paralin** [comment]
Please spin a new release with the Twitch client!

**Comment by PFCKrutonium** [comment]
Can confirm, would be helpful.

**Comment by martinmine** [comment]
Would be great if this got fixed as I can't implement the TwitchIrcClient myself since the functions I need to override are protected.

**Comment by alexreg** [comment]
Sorry for the lack of activity. I’m really looking for a new maintainer to take over this project. So if anyone is interested, and feels qualified, please let me know.

**Comment by paralin** [comment]
I would be happy to take it over, I run a few major repositories.

My profile: https://github.com/paralin?tab=repositories

 - [Dota2](http://github.com/paralin/Dota2)
 - [Buildroot](https://github.com/paralin/buildroot)

I'm using it for a few projects as well.

**Comment by alexreg** [comment]
@paralin Great. Any chance you could join ##irc.net on Freenode so we could have a brief chat?

**Comment by paralin** [comment]
Yes, I can come on in a few hours if that's okay with you.

**Comment by alexreg** [comment]
Best we talk tomorrow, if you’re free then – it’s rather late here in Britain.

**Comment by PFCKrutonium** [comment]
_Waits Patiently_

**Comment by ArcaneWater** [comment]
Any news? Is it possible just to make a release with TwitchIrcClient?

**Comment by alexreg** [comment]
I’m currently in the process of handing over the project to @paralin, but we haven’t been able to complete it yet.

**Comment by paralin** [comment]
Okay, I'm working on the minor release 0.5.1 right now. 

A short term fix for this would be to release a new version with the current develop branch, that includes the Twitch client.

A long term fix is to make the overridden functions overrideable from other libraries. I think removing the internal specifier on these functions is a good option. There's no real reason to limit users' ability to override and polymorph the IRC client.

**Comment by paralin** [comment]
Version 0.6.0 was released.

**Comment by PFCKrutonium** [comment]
:dancer:
