### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by martinmine** [IrcDotNet/IrcDotNet#20]
Would be great if there was support for .NET Core. The compatibility report I got for the current code says ~96.8% compatibility, and those issues that are there should be relatively easy to fix such that the code can be compiled to .NET Core.

**Comment by paralin** [comment]
Will work on this for the next major version.

**Comment by martinmine** [comment]
Awesome!

**Comment by paralin** [comment]
I have nearly everything working but I can't resolve "system.security.cryptography.x509certificates" under the "dotnet" platform... Any ideas?

**Comment by martinmine** [comment]
All I know is that my portability report says that its available under .NET Core, but not .Net 5 for some strange reason. I found a [post on Github](https://github.com/dotnet/coreclr/issues/31) stating that the crypto namespace you're referring to will be a nuget package you will have to reference for .NET Core as far as I understand it.

**Comment by benpye** [comment]
Did you look at this any further? I'm looking to use the library and I intend to see if I can get it working if it isn't already. That said with the latest announcements there will be a lot more of the API surface anyway.

**Comment by DarkKilauea** [comment]
See pull request #26 for a potential fix for this issue.

Hopefully I'm not stomping on any feet here.

**Comment by paralin** [comment]
Merged into chore/dotnetcore

**Comment by paralin** [comment]
Completed.
