### ISSUE TITLE
Server NOTICE causes Null Reference Exception in IrcTargetMask.cs

### ISSUE THREAD

**Issue by Sukasa** [IrcDotNet/IrcDotNet#22]
Receiving the following NOTICE on an IRC network lead to an NRE:

`:Global!services@service.irchighway.net NOTICE $* :IdleRPG is back! Join #idle-rpg to sign up and play`

This appears to be because on line 43, `this.mask = mask.Substring(1);`, `this.mask` is null.  A quick workaround I applied at run-time, `this.mask = mask != null ? mask.Substring(1) : "";`, allowed me to at least shut the program down gracefully immediately thereafter.

**Comment by paralin** [comment]
Thanks, this will be patched in the next version.
