### ISSUE TITLE
ONOTICE crash

### ISSUE THREAD

**Issue by ghost** [IrcDotNet/IrcDotNet#25]
There's a crash that happens when an ONOTICE is sent to a channel that an IrcClient is in. I'm not sure if it's a server-specific things, but on SwiftIRC, ONOTICEs send a NOTICE @#SwiftChannel <message>, which causes IrcDotNet to throw 

```
Unhandled Exception: System.ArgumentException: The source '@#SwiftChannel' of the message was not recognised as either a server or user.
```

**Comment by paralin** [comment]
Interesting, Definitely a bug to fix.

**Comment by internetbird** [comment]
Hi @nerii  ,@paralin . I want to help with this. How can I reproduce this bug?  I ran an IRCBot in a SwiftIRC channel and sent an ONOTICE but the bot didn't crash...

**Comment by paralin** [comment]
@nerii can we get a message to reproduce?

**Comment by nerii** [comment]
@internetbird Probably a stupid question, but is the bot OPed? (+o) It crashes with any onotice in any channel for me.

http://puu.sh/pR9x9.png

**Comment by internetbird** [comment]
@nerii  ,yes. The bot is OPed and it receives the notice. I send the notice with mirc client. Do you send it with an IrcDotNet client?

**Comment by nerii** [comment]
@internetbird Nope, I use mirc as well.

**Comment by oreleraki** [comment]
fixed.
