### ISSUE TITLE
Missing Constructor and Connect method

### ISSUE THREAD

**Issue by AlaskanDruid** [IrcDotNet/IrcDotNet#32]
The current Nuget release is missing the constructor:

"Cannot create an instance of the abstract class or interface 'IrcClient'

Using...

`IrcClient client = new IrcClient();`

The connect method is also missing between:

IrcClient.ClientInfoReceived
IrcClient.Connected

**Comment by paralin** [comment]
It's an abstract class, you can't construct it, correct?

**Comment by txdv** [comment]
Use StandardIrcClient.

IrcClient has all the logic, StandardIrcClient ties the logic to the sockets
