### ISSUE TITLE
Target .NET core

### ISSUE THREAD

**Issue by agc93** [IrcDotNet/IrcDotNet#34]
Although the code includes a `project.json` targeting `netstandard1.5` (presumably as a result of #20 ), the package on NuGet seems to still be targeting .NET Framework and DNX targets. Will there be an updated NuGet package to support `netstandard` since we can't currently install this package into a .NET Core project?

**Comment by paralin** [comment]
Please see #35

Feel free to PR

**Comment by paralin** [comment]
We did actually upgrade the project to the new dotnet CLI, but there were outstanding issues with it that I had not fixed yet, so it has not been pushed to nuget yet. 

See the other issue, I'm going to try to get a new version up tomorrow.

**Comment by paralin** [comment]
Closing this issue in favor of the other linked above.
