### ISSUE TITLE
Finish upgrade to dotnet 1.0 and push to NuGet

### ISSUE THREAD

**Issue by paralin** [IrcDotNet/IrcDotNet#35]
I previously made attempts to upgrade this package to .NET Core as well as to upgrade the tooling to the latest, as defined by dotnet. The issue is that they decided some time ago to move away from `package.json` just after everyone had finished migrating to it. During the rc phase of dotnet, each RC version completely broke everything using the previous version, with no easy way of upgrading code between versions without hours and hours of effort, even for something simple like IrcDotNet.

I have not used C# for any new projects since the announcement of moving off of package.json. As such, I'm no longer using IrcDotNet for any of my projects, so updates to this are a bit sparse right now. 

If those of you using this package have urgent fixes that need to be released for you to continue work, please feel free to make PRs. I will review them and publish once the necessary work to upgrade everything to dotnet 1.0 is complete.

**Comment by paralin** [comment]
Steps required to proceed below:

 - [ ] There is a [dotnet migrate](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-migrate) tool, investigate if this is applicable to this project
 - [ ] Decide if we need to wait for dotnet v2 or not.

**Comment by paralin** [comment]
The migrate tool succeeded, but compilation fails. The library itself compiled fine, but the samples do not. 

This is promising, I will try to iron out the remaining errors tomorrow and push to nuget when I have a stable build + tests. 

I can only hope the NUnit tests don't need to be rewritten.

**Comment by paralin** [comment]
Tests have to be significantly modified to fit under the new dotnet testing framework. Working on that now.

**Comment by agc93** [comment]
Any movement on this @paralin or work we can help with? I'd love to use this with one of my libraries, but it's on `netstandard` already :/

**Comment by paralin** [comment]
https://github.com/IrcDotNet/IrcDotNet/pull/42

That's part #1 of the upgrade. 

Been stalled for a few days since I'm crazy busy right now, but I'm pushing to finish it soon.

**Comment by agc93** [comment]
No problem, thanks for the update @paralin !

**Comment by paralin** [comment]
@agc93 Done, please have a try and make an issue if anything is broken.
