### ISSUE TITLE
Change IRC commands to uppercase(?)

### ISSUE THREAD

**Issue by chrboe** [IrcDotNet/IrcDotNet#38]
When implementing #37, I noticed that the library currently sends all IRC commands in lowercase. The spec uses uppercase commands in all examples, and most implementations send commands in uppercase. I therefore suggest changing all of the commands to uppercase (I'd be happy to contribute a PR for this if it is confirmed that this doesn't raise any ideological concerns)

**Comment by paralin** [comment]
Sounds fine, PR please.

**Comment by paralin** [comment]
By the way, in your PR commit in the body please provide some references (maybe just a couple links to some examples showing the uppercase)
