### ISSUE TITLE
StandardIrcClient.Connect should not be protected.

### ISSUE THREAD

**Issue by RheaAyase** [IrcDotNet/IrcDotNet#45]
Hi guys, how are you supposed to instinctively connect the client to a server without this method? Just curious. Oh and. Make it public. Cheers! =)

**Comment by RheaAyase** [comment]
Oh hey nevermind, it's just a copypasta code that doesn't override/call base.Connect in any way. Very confusing... Still consider it as a feedback to the... design of the whole thing?

**Comment by oliverbooth** [comment]
I apologise for necro'ing this issue but I have feelings.

Why the hell is it `protected`? Every single sample I've seen, even [the ones in this repo](https://github.com/IrcDotNet/IrcDotNet/blob/master/samples/IrcDotNet.Samples.TwitchChat/Program.cs), show a simple construction of the `IrcClient` and then calling `Connect`.

I am completly lost for words at how difficult it is just to make a simple **CONNECTION.** Seriously, how is this supposed to be achieved???

Who designed this API?! This is not intuitive.

**Comment by oliverbooth** [comment]
Oh right and the severely lackluster documentation.

[Seriously?](https://ircdotnet.github.io/IrcDotNet/references/ircdotnet-twitchircclient.html)
