### ISSUE TITLE
.NET 4 Compatibility

### ISSUE THREAD

**Issue by Rusty-Shackleford** [IrcDotNet/IrcDotNet#48]
Hello, I've tried to include IrcDotNet in various c# solutions and it fails.  I've attempted to target every version of the .NETFramework from 4.0 up.  I even downloaded the zip archive of this repo and cannot get your solution to load in VS2015 or 2017.  I've never had that issue before with other projects, so I'm not sure what I'm doing wrong here...

I get the standard error:

> Could not install package 'IrcDotNet 0.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by paralin** [comment]
We don't target .net 4 right now. It will likely be included in the next release. The issue is that the dotnet tooling is not particularly good at targeting older versions of .net after we upgraded the package to be compatible with .net standard.

**Comment by Rusty-Shackleford** [comment]
The documentation says:

> client library for the .NET Framework 4.0

Which framework should I use?

**Comment by Rusty-Shackleford** [comment]
Appreciate the help btw, really hoping to use this!  :)

**Comment by paralin** [comment]
You should use .Net Core - which is .Net Standard, Microsoft's new cross platform open source version of .NET: https://www.microsoft.com/net/core

**Comment by Rusty-Shackleford** [comment]
Ok that clears it up, I've just not had a use-case for Core yet.  Now I do!  Thanks for your help, sorry for the noob question.
