### ISSUE TITLE
Bug in the regex for serverName

### ISSUE THREAD

**Issue by clausjoergensen** [IrcDotNet/IrcDotNet#62]
The current regex for parsing the server name (regexServerName) is "([^%@]+?\.[^%@]*)", however that returns a positive match for a user where the userName contains a dot (".") within the characters provided by the server. Example:

Windcape!claus.joer@Clk-7E3F3D83

Here the regex matches "Windcape!claus.joer", resulting in the Source being assumed to be a server, when it's in fact, a user.

**Comment by chrboe** [comment]
Are you sure that this username is valid?

Quoting RFC 1459 (Internet Relay Chat Protocol):
```
   <target>     ::= <to> [ "," <target> ]
   <to>         ::= <channel> | <user> '@' <servername> | <nick> | <mask>
   <channel>    ::= ('#' | '&') <chstring>
   <servername> ::= <host>
   <host>       ::= see RFC 952 [DNS:4] for details on allowed hostnames
   <nick>       ::= <letter> { <letter> | <number> | <special> }
   <mask>       ::= ('#' | '$') <chstring>
   <chstring>   ::= <any 8bit code except SPACE, BELL, NUL, CR, LF and
                     comma (',')>

   Other parameter syntaxes are:

   <user>       ::= <nonwhite> { <nonwhite> }
   <letter>     ::= 'a' ... 'z' | 'A' ... 'Z'
   <number>     ::= '0' ... '9'
   <special>    ::= '-' | '[' | ']' | '\' | '`' | '^' | '{' | '}'
```

Notice how `nick` is defined as `<letter> { <letter> | <number> | <special> }`, which doesn't include spaces.

That being said, I'm not sure how we should deal with this, even if it's non-compliant. The fact of the matter is that we simply can't decide whether something is a domain or a username purely based on a string check (*technically* a domain name doesn't even have to include a dot, think `localhost`).

**Comment by clausjoergensen** [comment]
Popular clients like mIRC uses the "email" provided as the UserName. 

>  The fact of the matter is that we simply can't decide whether something is a domain or a username purely based on a string check 

But you do. `IrcClient.GetSourceFromPrefix(..)` relies on the parsing logic being correct. If it parses out the UserHost as a ServerName, it'll return the wrong source.

**Comment by chrboe** [comment]
Right, I mixed some stuff up there. `nick` is the part before the `!`, `username` is the part after it.

I [tested the regex](https://regex101.com/r/foumbT/1), and it seems to be identifying the prefix parts just fine. What's a little curious is what follows after:

https://github.com/IrcDotNet/IrcDotNet/blob/1224728583e5f9e69b1a4c957e9f03a4ce524db9/source/IrcDotNet/IrcClient.cs#L963

If the regex finds a hostname, the source is automatically assumed to be the host...

**Comment by chrboe** [comment]
It really seems like the logic is correct... (see https://ideone.com/PWoN7q)

Can you try and debug your test setup in order to find out what serverName, nickName,... are at this line? https://github.com/IrcDotNet/IrcDotNet/blob/1224728583e5f9e69b1a4c957e9f03a4ce524db9/source/IrcDotNet/IrcClient.cs#L961

**Comment by clausjoergensen** [comment]
Sure, let me try and revisit the logic. I'll re-open if I can make a reproduction.
