### ISSUE TITLE
Turkish capital "i" problem

### ISSUE THREAD

**Issue by ornitorenk** [IrcDotNet/IrcDotNet#64]
When I try to connect to a server via a machine with Turkish culture I see raw output messages with error of:
"451 NİCK :You have not registered"

Or when I try to join a channel using client.Channels.Join() it says:
"JOİN :Unknown command"

I think there is a problem regarding to Turkish capital i problem.
Commands should be NICK or JOIN not NİCK or JOİN

More info: https://haacked.com/archive/2012/07/05/turkish-i-problem-and-why-you-should-care.aspx/

**Comment by txdv** [comment]
```csharp
"join".ToUpper(new CultureInfo("tr-TR"))
```
returns JOİN, I guess you are right, somewhere ToUpper with culture is called and it doesn't make sense
