### ISSUE TITLE
Event Handlers are being called from a different thread.

### ISSUE THREAD

**Issue by hypodyne** [IrcDotNet/IrcDotNet#65]
I am trying to replace another irc library with your library.  I am using it with Mono.
It seems to connect okay, but when an event handler, receives an event and I go to update the user interface, I get an "xxx can only be called from the main thread". 

I don't know much about threading, but it seems to me that you should be returning the event on the main thread.

`public void Connect(Server server, bool useSsl, Profile userProfile)
    {
        // if already connected?

        IrcUserRegistrationInfo user = new IrcUserRegistrationInfo();
        user.UserName = userProfile.username;
        user.NickName = userProfile.nickname;
        user.RealName = userProfile.realname;
        user.Password = userProfile.password;

        ircClient = new StandardIrcClient();
        ircClient.FloodPreventer = new IrcStandardFloodPreventer(4, 2000);
        ircClient.Connected += ircClient_Connected;
      //  ircClient.ConnectFailed += ircClient_ConnectFailed;
      ///  ircClient.Disconnected += ircClient_Disconnected;
      //  ircClient.Error += ircClient_Error;
     //   ircClient.ProtocolError += ircClient_ProtocolError;
     //   ircClient.Registered += ircClient_Registered;
     //   ircClient.MotdReceived += ircClient_MotdReceived;
     //   ircClient.NetworkInformationReceived += ircClient_NetworkInformationReceived;
      //  ircClient.ServerVersionInfoReceived += ircClient_ServerVersionInfoReceived;
      //  ircClient.ServerTimeReceived += ircClient_ServerTimeReceived;
     //   ircClient.ServerLinksListReceived += ircClient_ServerLinksListReceived;
    //    ircClient.ServerStatsReceived += ircClient_ServerStatsReceived;
     //   ircClient.WhoReplyReceived += ircClient_WhoReplyReceived;
     //   ircClient.WhoIsReplyReceived += ircClient_WhoIsReplyReceived;
     //   ircClient.WhoWasReplyReceived += ircClient_WhoWasReplyReceived;
      //  ircClient.ChannelListReceived += ircClient_ChannelListReceived;

        if (useSsl && server.sslPorts.Length > 0)
        {
            ircClient.Connect(server.hostName, server.sslPorts[0], true, user);
        }
        else if (useSsl == false && server.ports.Length > 0)
        {
            ircClient.Connect(server.hostName, server.ports[0], false, user);
        }
    }

private void ircClient_Connected(object sender, EventArgs e)
    {
        txtSend.enabled = true; // ERROR

    }
`

**Comment by Insire** [comment]
When you have a user interface like winforms or wpf(or any UI framework that i know off), its your task as developer to make sure that you talk with your UI on the correct thread/ context. Its not the task of any library to mess with that.

**Comment by chrboe** [comment]
On a more practical note, you should use the `Invoke` method to run your function on the correct thread.

**Comment by Insire** [comment]
for WPF it is [System.Windows.Application](https://docs.microsoft.com/en-us/dotnet/api/system.windows.application?view=netframework-4.7.2).Dispatcher.Invoke(someAction);

**Comment by hypodyne** [comment]
It's unity 3D game engine. What does that use? I don't know.

In this client [https://github.com/cshivers/IrcClient-csharp/blob/master/IrcClient-csharp/IrcClient.cs](https://github.com/cshivers/IrcClient-csharp/blob/master/IrcClient-csharp/IrcClient.cs) I did not have any problems. See line 56 and 153. It handles it for the user.  The only reason I am not using that is because it has a viral license.

You guys have a lot more chance of doing the threading correctly, than I do.

**Comment by hypodyne** [comment]
Okay, worked out how to use it with unity. 

Thanks for the feedback.
