### ISSUE TITLE
nick changed event

### ISSUE THREAD

**Issue by hypodyne** [IrcDotNet/IrcDotNet#71]
Requested feature: 

When sending a user nickname changed event, add a new eventArgs with the oldNickname and newNickname. 

Can't see how its of any use without this information.

You have the IrcUser as sender, which will contain the new nickname, but not the old nickname. I have to find the string in a UI list to change it.

**Comment by txdv** [comment]
Do you want to try to do a pull request for this?

**Comment by oreleraki** [comment]
@hypodyne, feature has been added.
