### ISSUE TITLE
Sending an invite command not working

### ISSUE THREAD

**Issue by Sonic3R** [IrcDotNet/IrcDotNet#75]
Hi,

I'm happy to use this library for connecting to different irc servers. But I want to connect to a channel which is invite based, the invite command looks like:
`/msg botname invite XXXXXXXXXXXAAAAXXXX`

I have the following code where I tried to send command but no success:

```
var uri = new Uri(ircUrl, UriKind.Absolute);

IrcUserRegistrationInfo info = new IrcUserRegistrationInfo
{
	NickName = _nick,
	Password = _password,
	RealName = _nick,
	UserName = _nick
};

_client.RawMessageReceived += (s, ev) =>
{
	write(ev.RawContent);
};


_client.Registered += (s, ev) =>
{
        _client.SendRawMessage("/msg bot invite XXXXXXXAAAAAXXXXXXX");
	_client.Channels.Join(_channel);
};

_client.Connect(uri, info);
```
Seems that `msg` is unknown command ... how's that ?

How to achieve this ?

**Comment by oreleraki** [comment]
This is not a bug, but a misuse of the Protocol.
Use:
`_client.SendRawMessage(INVITE Nickname #Channel)`

**Comment by Sonic3R** [comment]
That is special command in order to be able to join a channel. To be in a channel you must be invited by using command `/msg botname invite THIS_UNIQUE_CODE` ...

So, in this case how to send such command ?

**Comment by oreleraki** [comment]
Ok, but you need to understand "/msg" doesn't exists in actual protocol world, but only in client side implementations.

IRC Message are declared in the following format:
`PRIVMSG NICKNAME :MESSAGE` (including the colon ':')

So what you need is probably:
`_client.SendRawMessage("PRIVMSG botname :invite THIS_UNIQUE_CODE")`

**Comment by Sonic3R** [comment]
Yes, it is working !
